import { Game } from './game';

export const GAMES: Game[] = [
  { 
  id: 1, 
  name: 'Doom Ethernal', 
  price: 200, 
  description: 'Hells armies have invaded Earth. Become the Slayer in an epic single-player campaign to conquer demons across dimensions and stop the final destruction of humanity. The only thing they fear... is you.' , 
  game_type:'indie'},
  { id: 2, 
    name: 'Morrowind', 
    price: 200, 
    description: 'Hells armies have invaded Earth. Become the Slayer in an epic single-player campaign to conquer demons across dimensions and stop the final destruction of humanity. The only thing they fear... is you.', 
    game_type:'indie' },
  { id: 3, 
    name: 'Oblivion', 
    price: 200, 
    description: 'Hells armies have invaded Earth. Become the Slayer in an epic single-player campaign to conquer demons across dimensions and stop the final destruction of humanity. The only thing they fear... is you.', 
    game_type:'adventure' },
  { id: 4, 
    name: 'Skyrim', 
    price: 200, 
    description: 'Hells armies have invaded Earth. Become the Slayer in an epic single-player campaign to conquer demons across dimensions and stop the final destruction of humanity. The only thing they fear... is you.', 
    game_type:'adventure' },
  { id: 5, 
    name: 'Tanks', 
    price: 200, 
    description: 'Hells armies have invaded Earth. Become the Slayer in an epic single-player campaign to conquer demons across dimensions and stop the final destruction of humanity. The only thing they fear... is you.' , 
    game_type:'action'},
  { id: 6, 
    name: 'Dota', 
    price: 200, 
    description: 'Hells armies have invaded Earth. Become the Slayer in an epic single-player campaign to conquer demons across dimensions and stop the final destruction of humanity. The only thing they fear... is you.', 
    game_type:'action' }
];